import { SessionProvider } from "next-auth/react";
import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProviders } from "@/lib/context/Proivders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Nextjs Starter",
    description: "Generated by shuaib",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProviders>{children}</SessionProviders>
            </body>
        </html>
    );
}
